title:  "Millennial"
tagline: "a Jekyll theme"
description:

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Tutorials', file: 'resources.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Curriculum Vitae', file: 'CV.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/lucas-laughery-a091b149/'}
- {icon: 'envelope', link: 'mailto:la.laughery@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
